DIST_DIR=./dist
MAIN_PATH=./cmd/*.go
BINARY_NAME=main

.PHONY: clean build
build:
	@go build -o ${DIST_DIR}/${BINARY_NAME} ${MAIN_PATH} &&  echo ${BINARY_NAME} build success

.PHONY: run
run: 
	go run ${MAIN_PATH}

.PHONY: clean
clean:
	@go clean && rm ${DIST_DIR}/* && echo ${DIST_DIR} cleaned

	
