DIST_DIR=./dist
MAIN_PATH=./cmd/*.go
BINARY_NAME=main

build:
	go build -o ${DIST_DIR}/${BINARY_NAME} ${MAIN_PATH}

run: 
	go build -o ${DIST_DIR}/${BINARY_NAME} ${MAIN_PATH}
	${DIST_DIR}/${BINARY_NAME}

clean:
	go clean 
	rm ${DIST_DIR}/*

	
